# Generated by Django 4.0.3 on 2022-05-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_billinginfo_state_alter_billinginfo_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
