# Generated by Django 4.0.3 on 2022-05-30 15:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_billinginfo_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
