# Generated by Django 4.0.2 on 2022-03-05 11:53

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('img', models.ImageField(blank=True, null=True, upload_to=web.models.get_file_path)),
                ('product_name', models.CharField(max_length=50)),
                ('old_price', models.FloatField()),
                ('new_price', models.FloatField()),
                ('ratings', models.IntegerField()),
                ('status', models.BooleanField(default=False, help_text='0 = available, 1= not available')),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=150)),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_keywords', models.CharField(max_length=150)),
                ('meta_description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
