# Generated by Django 4.0.2 on 2022-03-05 16:32

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='big_description',
            field=models.TextField(default=web.models.texting2, max_length=3000),
        ),
        migrations.AddField(
            model_name='product',
            name='small_description',
            field=models.TextField(default=web.models.texting, max_length=500),
        ),
    ]
