# Generated by Django 4.0.3 on 2022-05-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_order_status_alter_order_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='company_name',
        ),
    ]
