# Generated by Django 4.0.3 on 2022-05-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_order_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
